---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaulidate-file
  namespace: vaulidate-file
  labels:
    app: vaulidate-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaulidate-file
  template:
    metadata:
      namespace: vaulidate-file
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vaulidate-file"
        vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/vaulidate/mysecret"
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- with secret "secret/data/vaulidate/mysecret" -}}
            postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
          {{- end -}}
            Using File Mode
      labels:
        app: vaulidate-file
    spec:
      serviceAccountName: vaulidate-file
      containers:
      - name: vaulidate
        image: wallacepf/vaulidate:latest
        env:
          - name: VAULT_MODE
            value: "file"
          - name: SECRET_FILE
            value: "/vault/secrets/config.txt"

---
apiVersion: v1
kind: Service
metadata:
  name: vaulidate-file
  namespace: vaulidate-file
spec:
  type: LoadBalancer
  selector:
    app: vaulidate-file
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080

# ---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: validate
#   namespace: vaulidate
# spec:
#   path: /
#   to:
#     kind: Service
#     name: vaulidate
#   port:
#     targetPort: 8080

